// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRating(arg1) {
  return window['go']['main']['App']['CreateRating'](arg1);
}

export function GetAllRatings() {
  return window['go']['main']['App']['GetAllRatings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
