// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function CreateRating(arg1:number):Promise<number>;

export function GetAllRatings():Promise<Array<repository.Rating>>;

export function Greet(arg1:string):Promise<string>;
